/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wgpu_render_bundle_draw: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_set_pipeline: (a: number, b: bigint) => void;
export const wgpu_render_bundle_draw_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_set_bind_group: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const wgpu_render_bundle_set_vertex_buffer: (a: number, b: number, c: bigint, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_set_push_constants: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_insert_debug_marker: (a: number, b: number) => void;
export const wgpu_render_bundle_pop_debug_group: (a: number) => void;
export const wgpu_render_bundle_set_index_buffer: (a: number, b: bigint, c: number, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_push_debug_group: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd52673c132d3df70: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h8700bc3eb4f28bd9: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h167b69798ef3a563_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4c7e529c82a172f3: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
